"""Turn answers into deployment artifacts.

Every function here is pure: answers in, file contents out, no filesystem and no
subprocesses. That is what makes the generated output golden-testable without a
Docker daemon, and it is the reason this module holds no I/O helpers.
"""

from __future__ import annotations

import json
import secrets

from . import schemes
from .schemes import DNS_01, EXTERNAL_PROXY, HTTP_01, INTERNAL_CA, DNS_PROVIDERS, SIZINGS

CADDY_IMAGE_TAG = "kicad-prism-caddy-dns:2"

SECRET_KEYS = frozenset({"POSTGRES_PASSWORD", "SESSION_SECRET", "OIDC_CLIENT_SECRET"})


def generate_secret(length: int = 48) -> str:
    return secrets.token_urlsafe(length)[:length]


def normalise(answers: dict) -> dict:
    """Fill in every value that can be derived rather than asked for.

    Divergence between related settings is a recurring source of broken
    deployments: a PUBLIC_BASE_URL that does not match CORS_ORIGINS_STR, or a
    cookie Secure flag that contradicts the scheme. Deriving them removes the
    opportunity.
    """
    result = dict(answers)
    scheme = result["scheme"]
    hostname = result["hostname"]

    result.setdefault("http_port", "8080")
    result.setdefault("sizing", "small-team")
    result.setdefault("workspace_name", "KiCAD Prism")
    result.setdefault("acme_staging", scheme in (HTTP_01, DNS_01))

    base_url = f"https://{hostname}"
    result["public_base_url"] = base_url
    result["cors_origins"] = base_url
    result["session_cookie_secure"] = "true"
    result["redirect_uris"] = [
        f"{base_url}/auth/callback",
        f"{base_url}/oauth/oidc/callback",
    ]

    for key in ("session_secret", "postgres_password"):
        if not result.get(key):
            result[key] = generate_secret(48 if key == "session_secret" else 32)

    if scheme == DNS_01:
        result["caddy_image"] = CADDY_IMAGE_TAG
        provider = DNS_PROVIDERS[result["dns_provider"]]
        result["dns_provider_module"] = provider.module
    else:
        result["caddy_image"] = "caddy:2"

    result["runs_caddy"] = schemes.SCHEMES[scheme].runs_caddy
    return result


def render_env(example: str, answers: dict) -> str:
    """Rewrite .env.example in place, preserving its comments and ordering.

    Keys the operator did not set keep the template's documented defaults, so
    the generated file stays readable and reviewable rather than becoming a
    bare list of assignments.
    """
    values = env_values(answers)
    pending = dict(values)
    lines: list[str] = []

    for raw in example.replace("\r\n", "\n").split("\n"):
        stripped = raw.strip()
        if stripped and not stripped.startswith("#") and "=" in raw:
            key = raw.split("=", 1)[0].strip()
            if key in pending:
                lines.append(f"{key}={pending.pop(key)}")
                continue
        lines.append(raw)

    if pending:
        lines.append("")
        lines.append("# ===========================================")
        lines.append("# Added by scripts/prism_deploy")
        lines.append("# ===========================================")
        for key, value in pending.items():
            lines.append(f"{key}={value}")

    return "\n".join(lines).rstrip("\n") + "\n"


def env_values(answers: dict) -> dict[str, str]:
    """The settings this installer owns. Everything else keeps its default."""
    values: dict[str, str] = {
        "WORKSPACE_NAME": answers["workspace_name"],
        "AUTH_ENABLED": "true",
        "OIDC_ISSUER_URL": answers["oidc_issuer"],
        "OIDC_CLIENT_ID": answers["oidc_client_id"],
        "OIDC_CLIENT_SECRET": answers["oidc_client_secret"],
        "OIDC_PROVIDER_NAME": answers.get("oidc_provider_name", "SSO"),
        "BOOTSTRAP_ADMIN_USERS_STR": answers["bootstrap_admins"],
        "SESSION_SECRET": answers["session_secret"],
        "SESSION_COOKIE_SECURE": answers["session_cookie_secure"],
        "PUBLIC_BASE_URL": answers["public_base_url"],
        "CORS_ORIGINS_STR": answers["cors_origins"],
        "POSTGRES_PASSWORD": answers["postgres_password"],
        "PRISM_HTTP_PORT": answers["http_port"],
    }
    values.update(SIZINGS[answers["sizing"]].values)

    if answers["scheme"] == DNS_01:
        provider = DNS_PROVIDERS[answers["dns_provider"]]
        values["PRISM_CADDY_IMAGE"] = answers["caddy_image"]
        values[provider.env_var] = answers["dns_credential"]
        for key, value in answers.get("extra_provider_env", {}).items():
            values[key] = value

    return values


def render_caddyfile(answers: dict) -> str | None:
    """The proxy site config, or None when an external proxy terminates TLS."""
    scheme = answers["scheme"]
    if scheme == EXTERNAL_PROXY:
        return None

    hostname = answers["hostname"]
    header = (
        "# Generated by scripts/prism_deploy. Edits are overwritten on re-run.\n"
        f"# Scheme: {scheme}\n\n"
    )

    if scheme == INTERNAL_CA:
        tls_block = "\ttls /certs/prism.crt /certs/prism.key\n"
    elif scheme == DNS_01:
        provider = DNS_PROVIDERS[answers["dns_provider"]]
        resolvers = answers.get("dns_resolvers", "1.1.1.1 8.8.8.8")
        lines = ["\ttls {", f"\t\t{provider.directive}", f"\t\tresolvers {resolvers}"]
        if answers.get("acme_staging"):
            lines.append(f"\t\tca {schemes.STAGING_ACME}")
        lines.append("\t}")
        tls_block = "\n".join(lines) + "\n"
    else:
        if answers.get("acme_staging"):
            tls_block = "\ttls {\n" f"\t\tca {schemes.STAGING_ACME}\n" "\t}\n"
        else:
            tls_block = ""

    if tls_block:
        tls_block += "\n"

    forwarded_proto = "https" if scheme == INTERNAL_CA else "{scheme}"

    return (
        f"{header}{hostname} {{\n"
        f"{tls_block}"
        "\tencode gzip zstd\n"
        "\n"
        "\t# Large catalog imports and long-running semantic generation\n"
        "\trequest_body {\n"
        "\t\tmax_size 2GB\n"
        "\t}\n"
        "\n"
        "\treverse_proxy frontend:80 {\n"
        "\t\theader_up Host {host}\n"
        "\t\theader_up X-Real-IP {remote_host}\n"
        f"\t\theader_up X-Forwarded-Proto {forwarded_proto}\n"
        "\n"
        "\t\ttransport http {\n"
        "\t\t\tread_timeout 300s\n"
        "\t\t\twrite_timeout 300s\n"
        "\t\t}\n"
        "\t}\n"
        "}\n"
    )


def render_compose(answers: dict) -> str:
    """Compose overlay: loopback port bindings, plus the proxy when Caddy runs.

    `!override` replaces the port lists rather than appending to them. A plain
    merge would leave docker-compose.yml's 0.0.0.0 bindings in place alongside
    the loopback ones, so the app would still be reachable over plain HTTP.
    """
    port = answers["http_port"]
    blocks = [
        "# Generated by scripts/prism_deploy. Edits are overwritten on re-run.",
        f"# Scheme: {answers['scheme']}",
        "",
        "services:",
        "  backend:",
        "    ports: !override",
        '      - "127.0.0.1:8000:8000"',
        "",
        "  frontend:",
        "    ports: !override",
        f'      - "127.0.0.1:{port}:80"',
    ]

    if answers["runs_caddy"]:
        caddy = [
            "",
            "  caddy:",
            f"    image: {answers['caddy_image']}",
        ]
        if answers.get("dns_pin"):
            caddy += ["    dns:", f"      - {answers['dns_pin']}"]

        volumes = [
            "    volumes: !override",
            "      - ./generated/Caddyfile:/etc/caddy/Caddyfile:ro",
        ]
        if answers["scheme"] == INTERNAL_CA:
            volumes.append(f"      - {answers['certificate_dir']}:/certs:ro")
        volumes += [
            "      - caddy_data:/data",
            "      - caddy_config:/config",
        ]

        if answers["scheme"] == DNS_01:
            provider = DNS_PROVIDERS[answers["dns_provider"]]
            env_vars = [provider.env_var, *answers.get("extra_provider_env", {})]
            caddy.append("    environment:")
            for name in env_vars:
                caddy.append(f"      - {name}=${{{name}:?Set {name} in the generated .env}}")

        blocks += caddy + volumes

    return "\n".join(blocks) + "\n"


def compose_files(answers: dict) -> list[str]:
    """The -f arguments, in the order Compose must receive them."""
    files = ["docker-compose.yml"]
    if answers["runs_caddy"]:
        files.append("docker-compose.proxy.yml")
    files.append("generated/docker-compose.generated.yml")
    return files


def compose_command(answers: dict, *args: str) -> list[str]:
    command = ["docker", "compose", "--env-file", "generated/.env"]
    for path in compose_files(answers):
        command += ["-f", path]
    return command + list(args)


def render_plan(answers: dict) -> str:
    """A redacted record of the run, for re-runs and for support requests."""
    redacted = {
        key: ("<redacted>" if key in ("session_secret", "postgres_password", "oidc_client_secret", "dns_credential") else value)
        for key, value in answers.items()
    }
    redacted.pop("extra_provider_env", None)
    return json.dumps(redacted, indent=2, sort_keys=True) + "\n"


def render_next_steps(answers: dict) -> str:
    """Everything the installer deliberately does not do, with values filled in."""
    scheme = answers["scheme"]
    hostname = answers["hostname"]
    started = " ".join(compose_command(answers, "up", "-d", "--wait"))

    lines = [
        f"# Next steps for {hostname}",
        "",
        "The installer generated configuration and can start the stack. It does not",
        "change anything outside this directory. The following are yours to do.",
        "",
        "## 1. DNS",
        "",
    ]

    if scheme == DNS_01:
        lines += [
            f"Create an **A record** for `{hostname}` pointing at this host. DNS-01 proves",
            "domain control with a TXT record and does not create the A record for you.",
            "Internal DNS is sufficient; the address may be private.",
            "",
            "If the record lives in a public zone, it must be DNS-only, never proxied.",
        ]
    elif scheme == HTTP_01:
        lines += [
            f"Point `{hostname}` at this host's public address, and make ports 80 and 443",
            "reachable from the internet. HTTP-01 requires the CA to connect inbound.",
        ]
    else:
        lines += [f"Point `{hostname}` at this host on whichever DNS serves your users."]

    lines += ["", "## 2. Firewall", ""]
    if scheme == EXTERNAL_PROXY:
        lines += [
            f"Route your existing proxy to `http://127.0.0.1:{answers['http_port']}`.",
            "It must preserve the Host header and forward the public protocol.",
            "No inbound ports need opening on this host.",
        ]
    else:
        lines += [
            "Allow inbound TCP 443, and 80 for the HTTP-to-HTTPS redirect.",
            "",
            "```powershell",
            'New-NetFirewallRule -DisplayName "KiCAD Prism HTTPS" -Direction Inbound '
            "-Protocol TCP -LocalPort 443 -Action Allow -Profile Domain,Private -RemoteAddress LocalSubnet",
            "```",
            "",
            "```bash",
            "sudo ufw allow proto tcp to any port 443",
            "```",
        ]

    lines += [
        "",
        "## 3. Register the OIDC client",
        "",
        "Both redirect URIs must be registered with the identity provider:",
        "",
        "```text",
        *answers["redirect_uris"],
        "```",
        "",
        "The backend refuses to start if the issuer, client credentials, or session",
        "secret are incomplete. That is deliberate: starting anyway would serve every",
        "project without a login.",
    ]

    if scheme in (HTTP_01, DNS_01):
        lines += [
            "",
            "## 4. Certificate Transparency",
            "",
            f"Every publicly trusted certificate is logged, so `{hostname}` becomes",
            "publicly enumerable within minutes of issuance, even when the service itself",
            "is unreachable from the internet. Record this as a decision.",
        ]

    if answers.get("acme_staging"):
        lines += [
            "",
            "## 5. Leave staging",
            "",
            "This deployment is pointed at the Let's Encrypt **staging** CA, so browsers",
            "will not trust the certificate yet. That is correct for a first run.",
            "",
            "Once issuance succeeds, re-run the installer and answer 'no' to staging, then",
            "delete the Caddy data volume so the staging account is discarded:",
            "",
            "```bash",
            " ".join(compose_command(answers, "down")),
            "docker volume rm $(docker volume ls -q | grep caddy_data)",
            started,
            "```",
        ]

    if answers.get("dns_pin"):
        lines += [
            "",
            "## Pinned resolver",
            "",
            f"Container DNS is pinned to `{answers['dns_pin']}` because the default resolver",
            "returned filtered answers. This works, but it breaks silently if this host's",
            "network changes, and the failure surfaces only at certificate renewal.",
            "",
            "Ask the network team to exempt the ACME and DNS provider endpoints from",
            "filtering, then re-run without the pin.",
        ]

    lines += [
        "",
        "## Backups",
        "",
        "A complete installation needs all of:",
        "",
        "- the `prism-postgres-data` volume",
        "- `data/projects` and `data/ssh`",
        "- `generated/.env`",
        "- the `caddy_data` volume, which holds issued certificates",
        "",
    ]
    return "\n".join(lines)


def render_all(example: str, answers: dict) -> dict[str, str]:
    """Every artifact for this deployment, keyed by path relative to the root."""
    files = {
        "generated/.env": render_env(example, answers),
        "generated/docker-compose.generated.yml": render_compose(answers),
        "generated/deploy-plan.json": render_plan(answers),
        "generated/NEXT_STEPS.md": render_next_steps(answers),
    }
    caddyfile = render_caddyfile(answers)
    if caddyfile is not None:
        files["generated/Caddyfile"] = caddyfile
    return files
